# Generated by Django 2.1 on 2018-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181021_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
