# Generated by Django 2.1 on 2018-10-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
