# Generated by Django 2.1 on 2018-10-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181022_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
