# Generated by Django 2.1 on 2018-10-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
