# Generated by Django 2.1 on 2018-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181024_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
