# Generated by Django 2.1 on 2018-10-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_img2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
